// frontend/src/App.jsx
import React, { useState, useEffect, useCallback } from 'react'
import Chat from './components/Chat'
import Uploads from './components/Uploads'
import Settings from './components/Settings'
import ErrorBoundary from './components/ErrorBoundary'

// 全局状态管理
const AppContext = React.createContext()

// 安全的localStorage操作
const safeLocalStorage = {
  setItem: (key, value) => {
    try {
      localStorage.setItem(key, value)
      return true
    } catch (e) {
      console.warn('localStorage quota exceeded, cleaning up old data...')
      try {
        // 尝试清理旧数据
        const oldSessions = localStorage.getItem('luminar_sessions')
        if (oldSessions) {
          const sessions = JSON.parse(oldSessions)
          // 只保留最近10个会话
          const trimmedSessions = sessions.slice(0, 10)
          localStorage.setItem('luminar_sessions', JSON.stringify(trimmedSessions))
          // 重试保存
          localStorage.setItem(key, value)
          return true
        }
      } catch (cleanupError) {
        console.error('Failed to clean up localStorage:', cleanupError)
      }
      return false
    }
  },
  getItem: (key) => {
    try {
      return localStorage.getItem(key)
    } catch (e) {
      console.error('Failed to read from localStorage:', e)
      return null
    }
  },
  removeItem: (key) => {
    try {
      localStorage.removeItem(key)
    } catch (e) {
      console.error('Failed to remove from localStorage:', e)
    }
  }
}

export default function App() {
  const [tab, setTab] = useState('chat')
  const [chatKey, setChatKey] = useState(Date.now()) // 用于触发新建会话
  const [sessions, setSessions] = useState([]) // 存储会话历史
  const [chatMessages, setChatMessages] = useState([]) // 持久化聊天消息
  const [chatParams, setChatParams] = useState({ // 聊天参数
    top_k: 5,
    temperature: 0.7,
    top_p: 0.9,
    max_tokens: 2048,
    presence_penalty: 0.0,
    frequency_penalty: 0.0
  })

  // 从localStorage加载数据
  useEffect(() => {
    const savedSessions = safeLocalStorage.getItem('luminar_sessions')
    const savedMessages = safeLocalStorage.getItem('luminar_current_chat')
    
    if (savedSessions) {
      try {
        setSessions(JSON.parse(savedSessions))
      } catch (e) {
        console.error('Failed to parse sessions:', e)
      }
    }
    
    if (savedMessages) {
      try {
        setChatMessages(JSON.parse(savedMessages))
      } catch (e) {
        console.error('Failed to parse chat messages:', e)
      }
    }
  }, [])

  // 保存会话到localStorage - 使用useCallback避免依赖问题
  const saveSessionsToStorage = useCallback((newSessions) => {
    // 限制会话数量
    const trimmedSessions = newSessions.slice(0, 20)
    safeLocalStorage.setItem('luminar_sessions', JSON.stringify(trimmedSessions))
  }, [])

  // 保存当前聊天到localStorage - 使用useCallback
  const updateChatMessages = useCallback((messages) => {
    setChatMessages(messages)
    safeLocalStorage.setItem('luminar_current_chat', JSON.stringify(messages))
  }, [])

  // 新建会话功能
  const createNewAnalysis = () => {
    // 如果当前有聊天内容，先保存到会话历史
    if (chatMessages.length > 0) {
      const session = {
        id: Date.now(),
        timestamp: new Date().toLocaleString('zh-CN'),
        messages: chatMessages
      }
      const newSessions = [session, ...sessions]
      setSessions(newSessions)
      saveSessionsToStorage(newSessions)
    }
    
    // 清空当前聊天
    setChatMessages([])
    safeLocalStorage.removeItem('luminar_current_chat')
    
    // 生成新的会话ID
    const newSessionId = Date.now()
    // 更新chatKey以重新渲染Chat组件
    setChatKey(newSessionId)
    // 切换到聊天页面
    setTab('chat')
  }

  // 保存会话
  const saveSession = (sessionData) => {
    if (!sessionData || sessionData.messages.length === 0) return
    
    // 首先保存到当前聊天
    setChatMessages(sessionData.messages)
    safeLocalStorage.setItem('luminar_current_chat', JSON.stringify(sessionData.messages))
    
    const session = {
      id: Date.now(),
      timestamp: new Date().toLocaleString('zh-CN'),
      ...sessionData
    }
    
    const newSessions = [session, ...sessions]
    setSessions(newSessions)
    saveSessionsToStorage(newSessions)
  }

  return (
    <ErrorBoundary>
      <div className="min-h-screen bg-surface text-on-surface">
        {/* 侧边栏导航 */}
        <aside className="h-screen w-64 fixed left-0 top-0 bg-[#e6e8ea] dark:bg-slate-900 flex flex-col p-4 space-y-6 z-40">
          <div className="flex items-center space-x-3 mb-4 px-2">
            <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center text-on-primary">
              <span className="material-symbols-outlined">biotech</span>
            </div>
            <div>
              <h1 className="text-lg font-black text-[#006b5f] leading-tight">Ex-Agent</h1>
              <p className="text-[10px] font-semibold tracking-wider text-on-surface-variant opacity-70 uppercase">Precision Lab OS</p>
            </div>
          </div>
          <button onClick={createNewAnalysis} className="w-full py-3 px-4 bg-gradient-to-br from-primary to-primary-container text-on-black rounded-xl font-bold shadow-lg shadow-primary/20 flex items-center justify-center space-x-2 active:scale-95 transition-transform">
            <span className="material-symbols-outlined text-[20px]">add</span>
            <span className="font-manrope text-sm font-semibold tracking-wide">新建会话</span>
          </button>
        <nav className="flex-1 space-y-1">
          <button 
            onClick={() => setTab('chat')} 
            className={`flex items-center space-x-3 px-4 py-3 ${tab === 'chat' ? 'bg-white dark:bg-slate-800 text-[#006b5f] rounded-lg shadow-sm font-bold' : 'text-slate-600 dark:text-slate-400 hover:bg-[#f2f4f6] dark:hover:bg-slate-800 rounded-lg transition-all group'}`}
          >
            <span className="material-symbols-outlined group-hover:text-primary transition-colors" style={{ fontVariationSettings: tab === 'chat' ? 'FILL 1' : 'FILL 0' }}>chat_bubble</span>
            <span className="font-manrope text-sm font-semibold tracking-wide">对话</span>
          </button>
          <button 
            onClick={() => setTab('uploads')} 
            className={`flex items-center space-x-3 px-4 py-3 ${tab === 'uploads' ? 'bg-white dark:bg-slate-800 text-[#006b5f] rounded-lg shadow-sm font-bold' : 'text-slate-600 dark:text-slate-400 hover:bg-[#f2f4f6] dark:hover:bg-slate-800 rounded-lg transition-all group'}`}
          >
            <span className="material-symbols-outlined group-hover:text-primary transition-colors" style={{ fontVariationSettings: tab === 'uploads' ? 'FILL 1' : 'FILL 0' }}>database</span>
            <span className="font-manrope text-sm font-semibold tracking-wide">知识库</span>
          </button>
          <button 
            onClick={() => setTab('settings')} 
            className={`flex items-center space-x-3 px-4 py-3 ${tab === 'settings' ? 'bg-white dark:bg-slate-800 text-[#006b5f] rounded-lg shadow-sm font-bold' : 'text-slate-600 dark:text-slate-400 hover:bg-[#f2f4f6] dark:hover:bg-slate-800 rounded-lg transition-all group'}`}
          >
            <span className="material-symbols-outlined group-hover:text-primary transition-colors" style={{ fontVariationSettings: tab === 'settings' ? 'FILL 1' : 'FILL 0' }}>settings</span>
            <span className="font-manrope text-sm font-semibold tracking-wide">设置</span>
          </button>
        </nav>
        <div className="pt-4 border-t border-outline-variant/10 space-y-1">
          <a className="flex items-center space-x-3 px-4 py-3 text-slate-600 dark:text-slate-400 hover:bg-[#f2f4f6] dark:hover:bg-slate-800 rounded-lg transition-all" href="#">
            <span className="material-symbols-outlined">logout</span>
            <span className="font-manrope text-sm font-semibold tracking-wide">退出登录</span>
          </a>
        </div>
      </aside>

      {/* 主内容区域 */}
      <main className="ml-64 min-h-screen">
        {/* 顶部栏 */}
        <header className="flex justify-between items-center px-8 w-full sticky top-0 z-30 h-16 bg-[#f7f9fb] transition-colors duration-200">
          <div className="flex items-center space-x-4">
            <h2 className="font-manrope text-xl font-bold tracking-tighter text-[#006b5f] dark:text-[#04ae9c]">
              {tab === 'chat' && 'Remote Sense 通用助手'}
              {tab === 'uploads' && 'RS AI'}
              {tab === 'settings' && '系统设置'}
            </h2>
            {tab === 'settings' && (
              <div className="px-3 py-1 rounded-full bg-secondary-container text-on-secondary-container text-[10px] font-bold uppercase tracking-widest">v2.4.0-Stable</div>
            )}
            {tab === 'uploads' && (
              <>
                <div className="h-4 w-px bg-outline-variant opacity-30"></div>
                <div className="flex items-center gap-2 text-on-surface-variant font-medium text-sm tracking-tight">
                  <span className="material-symbols-outlined text-base">folder_open</span>
                  知识库 / 资产
                </div>
              </>
            )}
            {tab === 'chat' && (
              <>
                <div className="h-4 w-px bg-outline-variant/30"></div>
                <span className="text-sm font-medium text-on-surface-variant">会话</span>
              </>
            )}
          </div>
          <div className="flex items-center space-x-4 text-slate-500">
            <span className="material-symbols-outlined text-[20px]">notifications</span>
            <span className="material-symbols-outlined text-[20px]">help_outline</span>
          </div>
        </header>

        {/* 内容区域 */}
        <div className="flex-1 overflow-auto">
          {tab === 'chat' && <Chat 
            key={chatKey} 
            initialMessages={chatMessages}
            initialParams={chatParams}
            onMessagesChange={updateChatMessages}
            onParamsChange={setChatParams}
            onSessionEnd={saveSession} 
          />}
          {tab === 'uploads' && <Uploads />}
          {tab === 'settings' && <Settings />}
        </div>
      </main>

      {/* 浮动装饰 */}
      <div className="fixed top-20 right-[-100px] w-[500px] h-[500px] bg-primary/5 rounded-full blur-[120px] pointer-events-none -z-10"></div>
      <div className="fixed bottom-0 left-[-50px] w-[300px] h-[300px] bg-secondary-container/10 rounded-full blur-[100px] pointer-events-none -z-10"></div>
      </div>
    </ErrorBoundary>
  )
}

// frontend/src/App.vue
<template>
  <div class="min-h-screen bg-surface text-on-surface">
    <!-- 移动端侧边栏遮罩 -->
    <div v-if="sidebarOpen && isMobile" class="fixed inset-0 bg-black/50 z-40" @click="sidebarOpen = false"></div>

    <!-- 侧边栏导航 -->
    <aside 
      class="h-screen bg-[#e6e8ea] flex flex-col p-4 space-y-6 z-50 transition-all duration-300"
      :class="[
        sidebarOpen || !isMobile ? 'translate-x-0' : '-translate-x-full',
        isMobile ? 'fixed left-0 top-0 w-72' : 'w-64 fixed left-0 top-0'
      ]"
    >
      <div class="flex items-center justify-between mb-4 px-2">
        <div class="flex items-center space-x-3">
          <div class="w-10 h-10 rounded-xl bg-primary flex items-center justify-center text-on-primary">
            <span class="material-symbols-outlined">biotech</span>
          </div>
          <div>
            <h1 class="text-lg font-black text-[#006b5f] leading-tight">Ex-Agent</h1>
            <p class="text-[10px] font-semibold tracking-wider text-on-surface-variant opacity-70 uppercase">Precision Lab OS</p>
          </div>
        </div>
        <button v-if="isMobile" @click="sidebarOpen = false" class="p-2 hover:bg-surface-container rounded-lg">
          <span class="material-symbols-outlined">close</span>
        </button>
      </div>
      
      <button 
        @click="handleCreateNewSession" 
        class="w-full py-2.5 px-4 bg-primary text-on-primary rounded-xl font-bold shadow-lg shadow-primary/30 flex items-center justify-center space-x-2 active:scale-95 transition-transform border-2 border-primary/50 hover:bg-primary/90 hover:border-primary"
      >
        <span class="material-symbols-outlined text-lg">add</span>
        <span class="font-manrope text-sm font-semibold tracking-wide">新建会话</span>
      </button>
      
      <nav class="flex-1 space-y-1 overflow-y-auto">
        <router-link 
          to="/chat" 
          class="flex items-center space-x-3 px-4 py-2.5 rounded-lg transition-all group"
          :class="{
            'bg-white text-[#006b5f] rounded-lg shadow-sm font-bold': $route.path === '/chat',
            'text-slate-600 hover:bg-[#f2f4f6]': $route.path !== '/chat'
          }"
        >
          <span class="material-symbols-outlined text-lg group-hover:text-primary transition-colors" :style="{ fontVariationSettings: $route.path === '/chat' ? 'FILL 1' : 'FILL 0' }">chat_bubble</span>
          <span class="font-manrope text-sm font-semibold tracking-wide">对话</span>
        </router-link>
        
        <!-- 会话列表 -->
        <div v-if="$route.path === '/chat'" class="mt-4 px-2">
          <div class="flex items-center justify-between mb-2 px-2">
            <span class="text-[11px] font-bold text-slate-500 uppercase tracking-wider">历史会话</span>
            <button 
              @click="handleCreateNewSession" 
              class="p-1 hover:bg-surface-container rounded-md transition-colors"
              title="新建会话"
            >
              <span class="material-symbols-outlined text-sm">add</span>
            </button>
          </div>
          <div class="space-y-1 max-h-[40vh] overflow-y-auto">
            <div
              v-for="session in store.sessionHistory"
              :key="session.id"
              @click="handleLoadSession(session.id)"
              class="group flex items-start space-x-2 px-3 py-2.5 rounded-lg cursor-pointer transition-all"
              :class="{
                'bg-white text-[#006b5f] shadow-sm': store.currentSessionId === session.id,
                'text-slate-600 hover:bg-[#f2f4f6]': store.currentSessionId !== session.id
              }"
            >
              <span class="material-symbols-outlined text-lg mt-0.5 shrink-0" :style="{ fontVariationSettings: store.currentSessionId === session.id ? 'FILL 1' : 'FILL 0' }">
                chat
              </span>
              <div class="flex-1 min-w-0">
                <p class="text-sm font-semibold truncate">
                  {{ session.session_name }}
                </p>
                <p 
                  v-if="session.last_message_preview" 
                  class="text-[10px] text-slate-400 truncate mt-0.5"
                >
                  {{ session.last_message_preview }}
                </p>
                <div class="flex items-center gap-2 mt-0.5">
                  <span class="text-[9px] text-slate-400">
                    {{ formatSessionTime(session.updated_at) }}
                  </span>
                  <span v-if="session.message_count" class="text-[9px] text-slate-400">
                    {{ session.message_count }} 条消息
                  </span>
                </div>
              </div>
              <button 
                @click.stop="handleDeleteSession(session.id)"
                class="p-1 opacity-0 group-hover:opacity-100 hover:bg-red-50 rounded-md text-red-400 hover:text-red-500 transition-all"
                title="删除会话"
              >
                <span class="material-symbols-outlined text-sm">delete</span>
              </button>
            </div>
          </div>
          <div v-if="store.isLoading" class="px-3 py-2 text-center text-sm text-slate-400">
            <span class="material-symbols-outlined animate-spin text-base">progress_activity</span>
          </div>
          <div v-else-if="store.sessionHistory.length === 0 && store.isSessionsLoaded" class="px-3 py-4 text-center text-sm text-slate-400">
            暂无会话，开始新对话吧！
          </div>
        </div>
        
        <router-link 
          to="/uploads" 
          class="flex items-center space-x-3 px-4 py-2.5 rounded-lg transition-all group mt-4"
          :class="{
            'bg-white text-[#006b5f] rounded-lg shadow-sm font-bold': $route.path === '/uploads',
            'text-slate-600 hover:bg-[#f2f4f6]': $route.path !== '/uploads'
          }"
        >
          <span class="material-symbols-outlined text-lg group-hover:text-primary transition-colors" :style="{ fontVariationSettings: $route.path === '/uploads' ? 'FILL 1' : 'FILL 0' }">database</span>
          <span class="font-manrope text-sm font-semibold tracking-wide">知识库</span>
        </router-link>
        
        <router-link 
          to="/settings" 
          class="flex items-center space-x-3 px-4 py-2.5 rounded-lg transition-all group"
          :class="{
            'bg-white text-[#006b5f] rounded-lg shadow-sm font-bold': $route.path === '/settings',
            'text-slate-600 hover:bg-[#f2f4f6]': $route.path !== '/settings'
          }"
        >
          <span class="material-symbols-outlined text-lg group-hover:text-primary transition-colors" :style="{ fontVariationSettings: $route.path === '/settings' ? 'FILL 1' : 'FILL 0' }">settings</span>
          <span class="font-manrope text-sm font-semibold tracking-wide">设置</span>
        </router-link>
      </nav>
      
      <div class="pt-4 border-t border-outline-variant/10 space-y-1">
        <button @click="handleLogout" class="w-full flex items-center space-x-3 px-4 py-2.5 text-slate-600 hover:bg-[#f2f4f6] rounded-lg transition-all">
          <span class="material-symbols-outlined text-lg">logout</span>
          <span class="font-manrope text-sm font-semibold tracking-wide">退出登录</span>
        </button>
      </div>
    </aside>

    <!-- 主内容区域 -->
    <main 
      class="min-h-screen transition-all duration-300"
      :class="isMobile ? 'ml-0' : 'ml-64'"
    >
      <!-- 顶部栏 -->
      <header class="flex justify-between items-center px-4 md:px-8 w-full sticky top-0 z-30 h-16 bg-[#f7f9fb] transition-colors duration-200">
        <div class="flex items-center space-x-4">
          <button v-if="isMobile" @click="sidebarOpen = true" class="p-2 hover:bg-surface-container rounded-lg">
            <span class="material-symbols-outlined">menu</span>
          </button>
          <h2 class="font-manrope text-lg md:text-xl font-bold tracking-tighter text-[#006b5f]">
            {{ pageTitle }}
          </h2>
          <template v-if="$route.path === '/settings'">
            <div class="hidden sm:block px-3 py-1 rounded-full bg-secondary-container text-on-secondary-container text-[10px] font-bold uppercase tracking-widest">v2.4.0-Stable</div>
          </template>
          <template v-else-if="$route.path === '/uploads'">
            <div class="hidden sm:block h-4 w-px bg-outline-variant opacity-30"></div>
            <div class="hidden sm:flex items-center gap-2 text-on-surface-variant font-medium text-sm tracking-tight">
              <span class="material-symbols-outlined text-base">folder_open</span>
              知识库 / 资产
            </div>
          </template>
          <template v-else-if="$route.path === '/chat'">
            <div class="hidden sm:block h-4 w-px bg-outline-variant/30"></div>
            <span class="hidden sm:inline text-sm font-medium text-on-surface-variant">会话</span>
          </template>
        </div>
        <div class="flex items-center space-x-2 md:space-x-4 text-slate-500">
          <span class="material-symbols-outlined text-[20px]">notifications</span>
          <span class="material-symbols-outlined text-[20px]">help_outline</span>
        </div>
      </header>

      <!-- 内容区域 -->
      <div class="flex-1 overflow-auto">
        <router-view />
      </div>
    </main>

    <!-- 浮动装饰 -->
    <div class="fixed top-20 right-[-100px] w-[500px] h-[500px] bg-primary/5 rounded-full blur-[120px] pointer-events-none -z-10"></div>
    <div class="fixed bottom-0 left-[-50px] w-[300px] h-[300px] bg-secondary-container/10 rounded-full blur-[100px] pointer-events-none -z-10"></div>
  </div>
</template>

<script setup>
import { computed, ref, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAppStore } from './stores/appStore'
import { authService } from './services/auth'

const router = useRouter()
const store = useAppStore()
const sidebarOpen = ref(false)
const windowWidth = ref(window.innerWidth)

const isMobile = computed(() => windowWidth.value < 768)

const pageTitle = computed(() => {
  if (router.currentRoute.value.path === '/chat') return 'Remote Sense 通用助手'
  if (router.currentRoute.value.path === '/uploads') return 'RS AI'
  if (router.currentRoute.value.path === '/settings') return '系统设置'
  return ''
})

const handleResize = () => {
  windowWidth.value = window.innerWidth
  if (!isMobile.value) {
    sidebarOpen.value = false
  }
}

function formatSessionTime(isoString) {
  if (!isoString) return ''
  const date = new Date(isoString)
  const now = new Date()
  const diff = now - date
  const days = Math.floor(diff / (1000 * 60 * 60 * 24))
  
  if (days === 0) {
    return date.toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })
  } else if (days === 1) {
    return '昨天'
  } else if (days < 7) {
    return `${days}天前`
  } else {
    return date.toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' })
  }
}

async function handleLoadSession(sessionId) {
  console.log('[DEBUG] Loading session:', sessionId)
  await store.loadSession(sessionId)
  sidebarOpen.value = false
  // 确保路由在/chat
  if (router.currentRoute.value.path !== '/chat') {
    router.push('/chat')
  }
}

async function handleDeleteSession(sessionId) {
  console.log('[DEBUG] Deleting session:', sessionId)
  if (confirm('确定要删除这个会话吗？')) {
    await store.deleteSession(sessionId)
  }
}

function handleCreateNewSession() {
  console.log('[DEBUG] Creating new session...')
  store.createNewSession()
  sidebarOpen.value = false
  // 确保路由在/chat
  if (router.currentRoute.value.path !== '/chat') {
    router.push('/chat')
  }
  console.log('[DEBUG] New session created')
}

function createNewSession() {
  store.createNewSession()
  router.push('/chat')
}

function handleLogout() {
  authService.logout()
  router.push('/login')
}

onMounted(() => {
  window.addEventListener('resize', handleResize)
  // 仅在应用初始化时调用一次，避免重复初始化
  if (!store.isInitialized) {
    store.init()
    store.isInitialized = true
  }
})

onUnmounted(() => {
  window.removeEventListener('resize', handleResize)
})
</script>
